# CSV a SQL

En este archivo vamos a crear inserts de SQL a partir de datos de un CSV.

Vamos a seguir varios pasos:

+ Instalar dependencias nuevas.
+ Llenar tablas fuertes
+ Llenar tablas débiles

Ejemplo:

Voy a declarar una variable:

In [11]:
x = 5

Le voy a sumar 5 a x

In [9]:
x = x + 5

Voy a ver el valor de x:

In [12]:
x

5

Importación de librerías

In [2]:
import pandas as pd

Ruta global y lectura del dataset

In [3]:
ds_players = pd.read_csv('all_players.csv', sep=',')
ds_males = pd.read_csv('male_players.csv', sep=',')
ds_females = pd.read_csv('female_players.csv', sep=',')

C:\Users\ProfL3501\AppData\Local\Temp\ipykernel_44876\4195532570.py:1: DtypeWarning: Columns (33) have mixed types. Specify dtype option on import or set low_memory=False.
  ds_players = pd.read_csv('all_players.csv', sep=',')

Lista todos los jugadores

In [5]:
ds_players

,id,Rank,Name,OVR,PAC,SHO,PAS,DRI,DEF,PHY,...,League,Team,play style,url,GK Diving,GK Handling,GK Kicking,GK Positioning,GK Reflexes,Unnamed: 57
0,0,1,Kylian Mbappé,91,97,90,80,92,36,78,...,LALIGA EA SPORTS,Real Madrid,"Quick Step+, Acrobatic, Finesse Shot, Flair, R...",https,//www.ea.com/games/ea-sports-fc/ratings/player...,NaN,NaN,NaN,NaN,NaN
1,1,2,Rodri,91,66,80,86,84,87,85,...,Premier League,Manchester City,"Tiki Taka+, Aerial, Bruiser, Long Ball Pass, P...",https,//www.ea.com/games/ea-sports-fc/ratings/player...,NaN,NaN,NaN,NaN,NaN
2,2,4,Erling Haaland,91,88,92,70,81,45,88,...,Premier League,Manchester City,"Acrobatic+, Bruiser, Power Header, Power Shot,...",https,//www.ea.com/games/ea-sports-fc/ratings/player...,NaN,NaN,NaN,NaN,NaN
3,3,5,Jude Bellingham,90,80,87,83,88,78,83,...,LALIGA EA SPORTS,Real Madrid,"Relentless+, Flair, Intercept, Slide Tackle, T...",https,//www.ea.com/games/ea-sports-fc/ratings/player...,NaN,NaN,NaN,NaN,NaN
4,4,7,Vini Jr.,90,95,84,81,91,29,69,...,LALIGA EA SPORTS,Real Madrid,"Quick Step+, Chip Shot, Finesse Shot, First To...",https,//www.ea.com/games/ea-sports-fc/ratings/player...,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17732,17732,17146,Araya Dennis,53,42,57,49,52,25,42,...,Barclays WSL,Spurs,NaN,https,//www.ea.com/games/ea-sports-fc/ratings/player...,NaN,NaN,NaN,NaN,NaN
17733,17733,17146,Alexia Férnandez,53,53,55,51,53,34,47,...,Liga F,Granada CF,NaN,https,//www.ea.com/games/ea-sports-fc/ratings/player...,NaN,NaN,NaN,NaN,NaN
17734,17734,17146,Aleigh Gambone,53,60,58,53,56,49,53,...,Scottish Women's League,Glasgow City FC,NaN,https,//www.ea.com/games/ea-sports-fc/ratings/player...,NaN,NaN,NaN,NaN,NaN
17735,17735,17146,Joy Lysser,53,61,52,48,56,53,58,...,Schweizer Damen Liga,FC Zürich,NaN,https,//www.ea.com/games/ea-sports-fc/ratings/player...,NaN,NaN,NaN,NaN,NaN
17736,17736,17146,Kateřina Vithová,53,60,49,53,54,27,55,...,Ceska Liga Žen,Slavia Praha,NaN,https,//www.ea.com/games/ea-sports-fc/ratings/player...,NaN,NaN,NaN,NaN,NaN

Ejemplo para listar columnas por nombre

In [11]:
ds_players[['Name', 'Age']]

                   Name  Age
0         Kylian Mbappé   25
1                 Rodri   28
2        Erling Haaland   24
3       Jude Bellingham   21
4              Vini Jr.   24
...                 ...  ...
17732      Araya Dennis   18
17733  Alexia Férnandez   22
17734    Aleigh Gambone   23
17735        Joy Lysser   20
17736  Kateřina Vithová   18

[17737 rows x 2 columns]

Convertir la altura (182cm / 6'0") a 182

In [24]:
# x = '1::2::3'
# y = x.split('::') -> ['1','2','3']
alturas = ds_players['Height'] # list
for altura in alturas:
  # 182cm / 6'0"
  tmp = altura.split('cm')
  estatura = int(tmp[0])
  print(estatura/100, 'm')

1.82 m
1.91 m
1.95 m
1.86 m
1.76 m
1.81 m
1.88 m
1.78 m
1.96 m
1.93 m
2.0 m
1.74 m
1.93 m
1.87 m
1.75 m
1.71 m
1.69 m
1.76 m
1.87 m
1.85 m
1.82 m
1.88 m
1.73 m
1.88 m
1.9 m
1.77 m
1.95 m
1.93 m
1.86 m
1.84 m
1.78 m
1.77 m
1.84 m
1.75 m
1.85 m
1.81 m
1.91 m
1.79 m
1.83 m
1.83 m
1.9 m
1.8 m
1.95 m
1.72 m
1.83 m
1.87 m
1.9 m
1.86 m
1.74 m
1.82 m
1.88 m
1.71 m
1.72 m
1.76 m
1.73 m
1.78 m
1.8 m
1.74 m
1.95 m
1.85 m
1.87 m
1.77 m
1.9 m
1.93 m
1.78 m
1.8 m
1.88 m
1.85 m
1.86 m
1.82 m
1.92 m
1.68 m
1.8 m
1.83 m
1.72 m
1.75 m
1.79 m
1.99 m
1.89 m
1.92 m
1.77 m
1.9 m
1.89 m
1.78 m
1.83 m
1.91 m
1.88 m
1.88 m
1.78 m
1.81 m
1.8 m
1.81 m
1.92 m
1.87 m
1.8 m
1.7 m
1.76 m
1.95 m
1.75 m
1.81 m
1.8 m
1.89 m
1.8 m
1.76 m
1.8 m
1.74 m
1.89 m
1.72 m
1.73 m
1.8 m
1.87 m
1.87 m
1.81 m
1.92 m
1.86 m
1.74 m
1.78 m
1.92 m
1.8 m
1.77 m
1.79 m
1.78 m
1.86 m
1.92 m
1.85 m
1.78 m
1.85 m
1.94 m
1.9 m
1.83 m
1.85 m
1.72 m
1.86 m
1.75 m
1.83 m
1.82 m
1.81 m
1.87 m
1.89 m
1.8 m
1.7 m
1.88 m
1.72 m
1.89 m
1.85 m
1.93 m
1.89 m
1.85 m
1.93 m
1.84 m
1.81 m
1.9 m
1.94 m
1.83 m
1.77 m
1.8 m
1.89 m
1.87 m
1.84 m
1.85 m
1.76 m
1.78 m
1.77 m
1.9 m
1.8 m
1.9 m
1.86 m
1.73 m
1.82 m
1.86 m
1.73 m
1.85 m
1.99 m
1.73 m
1.92 m
1.77 m
1.83 m
1.76 m
1.85 m
1.85 m
1.79 m
1.75 m
1.81 m
1.92 m
1.8 m
1.92 m
1.85 m
1.66 m
1.73 m
1.71 m
1.78 m
1.77 m
1.88 m
1.76 m
1.86 m
1.73 m
1.87 m
1.78 m
1.87 m
1.9 m
1.93 m
1.75 m
1.81 m
1.78 m
1.86 m
1.91 m
1.97 m
1.8 m
1.71 m
1.73 m
1.84 m
1.71 m
1.83 m
1.8 m
1.85 m
1.83 m
1.7 m
1.88 m
1.93 m
1.78 m
1.8 m
1.75 m
1.78 m
1.91 m
1.88 m
1.72 m
1.96 m
1.89 m
1.76 m
1.83 m
1.7 m
1.91 m
1.88 m
1.84 m
1.76 m
1.85 m
1.79 m
1.84 m
1.83 m
1.87 m
1.84 m
1.77 m
1.86 m
1.75 m
1.86 m
1.89 m
1.7 m
1.74 m
1.91 m
1.9 m
1.78 m
1.89 m
1.75 m
1.76 m
1.85 m
1.87 m
1.84 m
1.81 m
1.85 m
1.85 m
1.89 m
1.87 m
1.88 m
1.8 m
1.88 m
1.91 m
1.81 m
1.72 m
1.94 m
1.95 m
1.91 m
1.82 m
1.95 m
1.89 m
1.86 m
1.86 m
1.93 m
1.91 m
1.86 m
1.61 m
1.87 m
1.82 m
1.89 m
1.95 m
1.82 m
1.75 m
1.87 m
1.75 m
1.89 m
1.86 m
1.73 m
1.91 m
1.83 m
1.75 m
1.84 m
1.89 m
1.69 m
1.78 m
1.85 m
1.78 m
1.81 m
1.82 m
1.78 m
1.81 m
1.82 m
1.88 m
1.83 m
1.84 m
1.74 m
1.84 m
1.89 m
1.75 m
1.83 m
1.91 m
1.77 m
1.73 m
1.91 m
1.91 m
1.82 m
1.83 m
1.87 m
1.92 m
1.86 m
1.78 m
1.9 m
1.83 m
1.85 m
1.83 m
1.69 m
1.91 m
1.86 m
1.8 m
1.87 m
1.74 m
1.85 m
1.85 m
1.88 m
1.87 m
1.92 m
1.72 m
1.86 m
1.76 m
1.82 m
1.79 m
1.92 m
1.73 m
1.85 m
1.83 m
1.8 m
1.8 m
1.8 m
1.8 m
1.81 m
1.73 m
1.89 m
1.7 m
1.87 m
1.92 m
1.8 m
1.92 m
1.84 m
1.79 m
1.89 m
1.81 m
1.86 m
1.85 m
1.8 m
1.91 m
1.85 m
1.82 m
1.8 m
1.8 m
1.68 m
1.9 m
1.77 m
1.89 m
1.72 m
1.78 m
1.9 m
1.81 m
1.82 m
1.87 m
1.91 m
1.73 m
1.83 m
1.78 m
1.75 m
1.96 m
1.81 m
1.77 m
1.85 m
1.87 m
1.72 m
1.86 m
1.77 m
1.88 m
1.8 m
1.76 m
1.8 m
1.87 m
1.78 m
1.85 m
1.78 m
1.8 m
1.75 m
1.88 m
1.87 m
1.85 m
1.87 m
1.85 m
1.9 m
1.71 m
1.88 m
1.77 m
1.83 m
1.93 m
1.8 m
1.78 m
1.94 m
1.71 m
1.84 m
1.97 m
1.69 m
1.81 m
1.94 m
1.79 m
1.72 m
1.75 m
1.93 m
1.88 m
1.86 m
1.71 m
1.84 m
1.92 m
1.75 m
1.73 m
1.87 m
1.86 m
1.72 m
1.89 m
1.87 m
1.87 m
1.74 m
1.85 m
1.88 m
1.9 m
1.87 m
1.84 m
1.75 m
1.98 m
1.85 m
1.95 m
1.77 m
1.8 m
1.88 m
1.86 m
1.86 m
1.78 m
1.84 m
1.72 m
1.81 m
1.81 m
1.8 m
1.9 m
1.8 m
1.9 m
1.89 m
1.92 m
1.72 m
1.78 m
1.74 m
1.83 m
1.79 m
1.87 m
1.76 m
1.85 m
1.81 m
1.82 m
1.78 m
1.85 m
1.93 m
1.78 m
1.8 m
1.95 m
1.8 m
1.99 m
1.83 m
1.85 m
1.78 m
1.94 m
1.79 m
1.81 m
1.7 m
1.88 m
1.92 m
1.85 m
1.72 m
1.85 m
1.73 m
1.8 m
1.7 m
1.78 m
1.88 m
1.9 m
1.82 m
1.8 m
1.92 m
1.77 m
1.68 m
1.78 m
1.84 m
1.8 m
1.81 m
1.95 m
1.77 m
1.81 m
1.67 m
1.8 m
1.85 m
1.79 m
1.7 m
1.82 m
1.76 m
1.74 m
1.83 m
1.81 m
1.88 m
1.91 m
1.88 m
1.8 m
1.88 m
1.87 m
1.85 m
1.81 m
1.76 m
1.87 m
1.91 m
1.83 m
1.88 m
1.84 m
1.79 m
1.74 m
1.73 m
1.86 m
1.84 m
1.79 m
1.89 m
1.9 m
1.88 m
1.72 m
1.84 m
1.89 m
1.84 m
1.87 m
1.97 m
1.78 m
1.72 m
1.92 m
1.83 m
1.82 m
1.85 m
1.92 m
1.82 m
1.82 m
1.78 m
1.78 m
1.95 m
1.72 m
1.96 m
1.8 m
1.79 m
1.77 m
1.84 m
1.73 m
1.87 m
1.91 m
1.79 m
1.88 m
1.9 m
1.78 m
1.88 m
1.87 m
1.94 m
1.94 m
1.72 m
1.81 m
1.85 m
1.82 m
1.71 m
1.83 m
1.72 m
1.88 m
1.89 m
1.83 m
1.84 m
1.95 m
1.91 m
1.95 m
1.7 m
1.9 m
1.88 m
1.92 m
1.86 m
1.87 m
1.93 m
1.84 m
1.8 m
1.79 m
1.79 m
1.85 m
1.72 m
1.79 m
1.83 m
1.73 m
1.86 m
1.76 m
1.9 m
1.82 m
1.81 m
1.75 m
1.93 m
1.84 m
1.75 m
1.95 m
1.96 m
1.74 m
1.81 m
1.74 m
1.8 m
1.83 m
1.8 m
1.75 m
1.78 m
1.94 m
1.9 m
1.75 m
1.73 m
1.86 m
1.84 m
1.85 m
1.81 m
1.65 m
1.72 m
1.87 m
1.87 m
1.88 m
1.75 m
1.79 m
1.81 m
1.86 m
1.9 m
1.72 m
1.87 m
1.98 m
1.77 m
1.88 m
1.74 m
1.65 m
1.92 m
1.84 m
1.8 m
1.75 m
1.83 m
1.78 m
1.88 m
1.9 m
1.9 m
1.94 m
1.72 m
1.9 m
1.74 m
1.79 m
1.82 m
1.82 m
1.68 m
1.82 m
1.72 m
1.97 m
1.68 m
1.9 m
1.75 m
1.82 m
1.82 m
1.72 m
1.69 m
1.9 m
1.69 m
1.76 m
1.79 m
1.77 m
1.81 m
1.8 m
1.9 m
1.93 m
1.9 m
1.75 m
1.84 m
1.79 m
1.82 m
1.76 m
1.85 m
1.82 m
1.92 m
1.91 m
1.77 m
1.91 m
1.77 m
1.87 m
1.63 m
1.76 m
1.72 m
1.86 m
1.93 m
1.84 m
1.82 m
1.78 m
1.84 m
1.83 m
1.81 m
1.81 m
1.77 m
1.87 m
1.81 m
1.75 m
1.83 m
1.82 m
1.85 m
1.78 m
1.89 m
1.87 m
1.8 m
1.94 m
1.8 m
1.93 m
1.8 m
1.86 m
1.93 m
1.82 m
1.81 m
1.9 m
1.79 m
1.91 m
1.85 m
1.83 m
1.85 m
1.84 m
1.85 m
1.85 m
1.78 m
1.92 m
1.75 m
1.86 m
1.76 m
1.8 m
1.84 m
1.83 m
1.82 m
1.9 m
1.78 m
1.69 m
1.8 m
1.91 m
1.8 m
1.72 m
1.84 m
1.76 m
1.88 m
1.83 m
1.74 m
1.84 m
1.8 m
1.92 m
1.79 m
1.82 m
1.8 m
1.68 m
1.94 m
1.85 m
1.78 m
1.87 m
1.8 m
1.84 m
1.85 m
1.83 m
1.72 m
1.82 m
1.76 m
1.83 m
1.94 m
1.92 m
1.88 m
1.83 m
1.84 m
1.99 m
1.87 m
1.77 m
1.87 m
1.84 m
1.89 m
1.82 m
1.75 m
1.9 m
1.9 m
1.9 m
1.69 m
1.9 m
1.84 m
1.75 m
1.86 m
1.92 m
1.87 m
1.72 m
1.73 m
1.88 m
1.9 m
1.85 m
1.89 m
1.91 m
1.81 m
1.76 m
1.72 m
1.78 m
1.75 m
1.68 m
1.85 m
1.85 m
1.88 m
1.88 m
1.97 m
1.96 m
1.8 m
1.93 m
1.72 m
1.95 m
1.9 m
1.89 m
1.96 m
1.7 m
1.91 m
1.87 m
1.82 m
1.76 m
1.82 m
1.83 m
1.83 m
1.75 m
1.91 m
1.85 m
1.87 m
1.8 m
1.85 m
1.95 m
1.83 m
1.81 m
1.85 m
1.78 m
1.87 m
1.75 m
1.66 m
1.78 m
1.9 m
1.78 m
1.88 m
1.77 m
1.73 m
1.73 m
1.8 m
1.8 m
1.85 m
1.75 m
1.78 m
1.94 m
1.84 m
1.78 m
1.79 m
1.85 m
1.83 m
1.74 m
1.79 m
1.88 m
1.78 m
1.87 m
1.71 m
1.9 m
1.8 m
1.78 m
1.82 m
1.82 m
1.79 m
1.76 m
1.7 m
1.84 m
1.85 m
1.79 m
1.87 m
1.68 m
1.94 m
1.88 m
1.88 m
1.96 m
1.83 m
1.85 m
1.75 m
1.7 m
1.83 m
1.82 m
1.82 m
1.75 m
1.86 m
1.79 m
1.86 m
1.85 m
1.83 m
1.8 m
1.9 m
1.82 m
2.0 m
1.75 m
1.88 m
1.8 m
1.94 m
1.94 m
1.71 m
1.9 m
1.73 m
1.86 m
1.89 m
1.8 m
1.75 m
1.86 m
1.8 m
1.73 m
1.82 m
1.87 m
1.91 m
1.75 m
1.76 m
1.74 m
1.81 m
1.93 m
1.81 m
1.83 m
1.9 m
1.83 m
1.72 m
1.83 m
1.76 m
2.02 m
1.75 m
1.74 m
1.91 m
1.75 m
1.88 m
1.85 m
1.72 m
1.91 m
1.73 m
1.68 m
1.88 m
1.79 m
1.7 m
1.75 m
1.89 m
1.8 m
1.76 m
1.92 m
1.79 m
1.72 m
1.94 m
1.85 m
1.87 m
1.86 m
1.84 m
1.83 m
1.86 m
1.93 m
1.87 m
1.78 m
1.69 m
1.81 m
1.92 m
1.77 m
1.68 m
1.87 m
1.71 m
1.78 m
1.76 m
1.81 m
1.82 m
1.77 m
1.73 m
1.92 m
1.92 m
1.83 m
1.8 m
1.91 m
1.83 m
1.76 m
1.78 m
1.74 m
1.9 m
1.79 m
1.88 m
1.84 m
1.81 m
1.72 m
1.75 m
1.82 m
1.87 m
1.76 m
1.92 m
1.86 m
1.94 m
1.7 m
1.87 m
1.87 m
1.75 m
1.77 m
1.78 m
1.85 m
1.85 m
1.83 m
1.85 m
1.87 m
1.9 m
1.8 m
1.76 m
1.79 m
1.73 m
1.87 m
1.92 m
1.79 m
1.91 m
1.81 m
1.97 m
1.77 m
1.86 m
1.82 m
1.88 m
1.83 m
1.89 m
1.96 m
1.75 m
1.79 m
1.64 m
1.75 m
1.8 m
1.83 m
1.96 m
1.83 m
1.83 m
1.73 m
1.78 m
1.89 m
1.69 m
1.83 m
1.88 m
1.81 m
1.87 m
1.7 m
1.72 m
1.72 m
1.74 m
1.81 m
1.83 m
1.84 m
1.85 m
1.85 m
1.85 m
1.72 m
1.98 m
1.85 m
1.8 m
1.88 m
1.78 m
1.78 m
1.95 m
1.87 m
1.84 m
1.75 m
1.83 m
1.75 m
1.75 m
1.96 m
1.81 m
1.96 m
1.71 m
1.78 m
1.68 m
1.65 m
1.78 m
1.78 m
1.73 m
1.75 m
1.75 m
1.85 m
1.77 m
1.78 m
1.81 m
1.82 m
1.83 m
1.83 m
1.86 m
1.89 m
1.88 m
1.82 m
1.9 m
1.81 m
1.89 m
1.77 m
1.84 m
1.88 m
1.75 m
1.87 m
1.9 m
1.81 m
1.9 m
1.76 m
1.89 m
1.8 m
1.78 m
1.89 m
1.9 m
1.87 m
1.78 m
1.77 m
1.66 m
1.82 m
1.82 m
1.73 m
1.8 m
1.73 m
1.85 m
1.78 m
1.78 m
1.8 m
1.92 m
1.84 m
1.75 m
1.85 m
1.76 m
1.86 m
1.7 m
1.94 m
1.87 m
1.77 m
1.93 m
1.74 m
1.88 m
1.83 m
1.74 m
1.78 m
1.88 m
1.69 m
1.85 m
1.8 m
1.75 m
1.72 m
1.8 m
1.85 m
1.86 m
1.87 m
1.85 m
1.88 m
1.8 m
1.78 m
1.88 m
1.75 m
1.71 m
1.84 m
1.86 m
1.96 m
1.73 m
1.86 m
1.82 m
1.76 m
1.85 m
1.78 m
1.86 m
1.72 m
1.89 m
1.8 m
1.76 m
1.85 m
1.89 m
1.85 m
1.96 m
1.87 m
1.9 m
1.96 m
1.78 m
1.81 m
1.81 m
1.86 m
1.69 m
1.87 m
1.67 m
1.74 m
1.72 m
1.8 m
1.72 m
1.87 m
1.93 m
1.69 m
1.82 m
1.84 m
1.78 m
1.9 m
1.82 m
1.77 m
1.76 m
1.83 m
1.79 m
1.8 m
1.73 m
1.82 m
1.82 m
1.84 m
1.67 m
1.75 m
1.74 m
1.91 m
1.95 m
1.71 m
1.85 m
1.96 m
1.75 m
1.8 m
1.71 m
1.75 m
1.8 m
1.91 m
1.9 m
1.88 m
1.79 m
1.9 m
1.79 m
1.83 m
1.81 m
1.85 m
1.86 m
1.9 m
1.91 m
1.8 m
1.85 m
1.92 m
1.75 m
1.88 m
2.01 m
1.75 m
1.82 m
1.88 m
1.78 m
1.94 m
1.73 m
1.67 m
1.8 m
1.84 m
1.91 m
1.84 m
1.91 m
1.87 m
1.88 m
1.94 m
1.86 m
1.88 m
1.86 m
1.69 m
1.91 m
1.92 m
1.69 m
1.78 m
1.86 m
1.72 m
1.93 m
1.76 m
1.8 m
1.7 m
1.85 m
1.78 m
1.91 m
1.9 m
1.8 m
1.76 m
1.76 m
1.78 m
1.85 m
1.85 m
1.85 m
1.91 m
1.68 m
1.92 m
1.7 m
1.8 m
1.81 m
1.92 m
1.81 m
1.68 m
1.86 m
1.8 m
1.74 m
1.82 m
1.78 m
1.96 m
1.73 m
1.8 m
1.81 m
1.85 m
1.81 m
1.78 m
1.73 m
1.78 m
1.85 m
1.89 m
1.84 m
1.93 m
1.8 m
1.99 m
1.79 m
1.73 m
1.91 m
1.85 m
1.88 m
1.83 m
1.76 m
1.91 m
1.82 m
1.78 m
1.87 m
1.84 m
1.82 m
1.9 m
1.7 m
1.79 m
1.78 m
1.93 m
1.84 m
1.85 m
1.76 m
1.75 m
1.84 m
1.82 m
1.7 m
1.7 m
1.83 m
1.79 m
1.79 m
1.75 m
1.72 m
1.76 m
1.92 m
1.72 m
1.79 m
1.82 m
1.84 m
1.85 m
1.82 m
1.79 m
1.78 m
1.84 m
1.79 m
1.75 m
1.84 m
1.7 m
1.78 m
1.76 m
1.75 m
1.7 m
1.9 m
1.88 m
1.82 m
1.8 m
1.81 m
1.88 m
1.88 m
1.89 m
1.79 m
1.86 m
1.92 m
1.86 m
1.78 m
1.86 m
1.75 m
1.68 m
1.93 m
1.8 m
1.71 m
1.81 m
1.79 m
1.68 m
1.77 m
1.79 m
1.81 m
1.88 m
1.84 m
1.93 m
1.79 m
1.84 m
1.89 m
1.79 m
1.81 m
1.9 m
1.8 m
1.91 m
1.87 m
1.89 m
1.7 m
1.93 m
1.83 m
1.87 m
1.88 m
1.96 m
1.72 m
1.73 m
1.75 m
1.97 m
1.91 m
1.95 m
1.75 m
1.67 m
1.84 m
1.81 m
1.86 m
1.91 m
1.91 m
1.83 m
1.87 m
1.81 m
1.84 m
1.85 m
1.93 m
1.73 m
1.73 m
1.86 m
1.74 m
1.8 m
1.86 m
1.78 m
1.75 m
1.87 m
1.82 m
1.75 m
1.82 m
1.78 m
1.73 m
1.7 m
1.83 m
1.69 m
1.78 m
1.85 m
1.95 m
1.94 m
1.76 m
1.91 m
1.82 m
1.77 m
1.87 m
1.8 m
1.89 m
1.78 m
1.77 m
1.88 m
1.95 m
1.85 m
1.83 m
1.81 m
1.75 m
1.9 m
1.85 m
1.87 m
1.9 m
1.81 m
1.71 m
1.89 m
1.8 m
1.83 m
1.9 m
1.91 m
1.91 m
1.81 m
1.9 m
1.89 m
1.89 m
1.93 m
1.8 m
1.9 m
1.83 m
1.75 m
1.78 m
1.82 m
1.81 m
1.85 m
1.85 m
1.75 m
1.63 m
1.7 m
1.88 m
1.94 m
1.88 m
1.81 m
1.89 m
1.92 m
1.82 m
1.82 m
1.81 m
1.75 m
1.8 m
1.77 m
1.81 m
1.88 m
1.9 m
1.83 m
1.85 m
1.91 m
1.72 m
1.8 m
1.71 m
1.83 m
1.71 m
1.78 m
1.77 m
1.93 m
1.78 m
1.88 m
1.72 m
1.87 m
1.91 m
1.81 m
1.84 m
1.77 m
1.77 m
1.9 m
1.78 m
1.68 m
1.79 m
1.95 m
1.75 m
1.84 m
1.85 m
1.85 m
1.9 m
1.85 m
1.97 m
1.78 m
1.75 m
1.72 m
1.73 m
1.8 m
1.84 m
1.75 m
1.75 m
1.8 m
1.78 m
1.97 m
1.88 m
1.87 m
1.84 m
1.76 m
1.92 m
1.77 m
1.76 m
1.82 m
1.69 m
1.63 m
1.97 m
1.78 m
1.7 m
1.68 m
1.8 m
1.78 m
1.84 m
1.8 m
1.79 m
1.88 m
1.86 m
1.81 m
1.93 m
1.85 m
1.73 m
1.75 m
1.9 m
1.81 m
1.75 m
1.9 m
1.77 m
1.78 m
1.75 m
1.87 m
1.81 m
1.86 m
1.9 m
1.85 m
1.76 m
1.95 m
1.93 m
1.87 m
1.87 m
1.81 m
1.84 m
1.88 m
1.92 m
1.86 m
1.72 m
1.92 m
1.88 m
1.7 m
1.86 m
1.71 m
1.82 m
1.71 m
1.73 m
1.84 m
1.83 m
1.82 m
1.68 m
1.87 m
1.89 m
1.68 m
1.78 m
1.91 m
1.85 m
1.85 m
1.87 m
1.75 m
1.73 m
1.91 m
1.69 m
1.86 m
1.78 m
1.88 m
1.88 m
1.85 m
1.88 m
1.7 m
1.73 m
1.8 m
1.85 m
1.78 m
1.75 m
1.72 m
1.89 m
1.68 m
1.81 m
1.75 m
1.75 m
1.86 m
1.82 m
1.77 m
1.78 m
1.72 m
1.89 m
1.79 m
1.93 m
1.72 m
1.82 m
1.9 m
1.82 m
1.84 m
1.92 m
1.78 m
1.77 m
1.87 m
1.73 m
1.67 m
1.86 m
1.74 m
1.78 m
1.84 m
1.8 m
1.78 m
1.93 m
1.94 m
1.83 m
1.82 m
1.73 m
1.89 m
1.9 m
1.8 m
1.64 m
1.94 m
1.83 m
1.9 m
1.75 m
1.82 m
1.89 m
1.68 m
1.9 m
1.95 m
1.96 m
1.75 m
1.92 m
1.82 m
1.73 m
1.8 m
1.83 m
1.83 m
1.9 m
1.76 m
1.75 m
1.73 m
1.73 m
1.81 m
1.8 m
1.81 m
1.88 m
1.92 m
1.79 m
1.85 m
1.74 m
1.95 m
1.56 m
1.9 m
1.7 m
1.89 m
1.9 m
1.81 m
1.66 m
1.9 m
1.76 m
1.76 m
1.88 m
1.86 m
1.85 m
1.91 m
1.77 m
1.75 m
1.77 m
1.8 m
1.8 m
1.77 m
1.83 m
1.93 m
1.91 m
1.86 m
1.9 m
1.85 m
1.73 m
1.77 m
1.91 m
1.86 m
1.84 m
1.82 m
1.85 m
1.7 m
1.83 m
1.7 m
1.75 m
1.75 m
1.7 m
1.82 m
1.74 m
1.82 m
1.71 m
1.8 m
1.82 m
1.87 m
1.81 m
2.0 m
1.87 m
1.86 m
1.83 m
1.75 m
1.86 m
1.73 m
1.77 m
1.8 m
1.91 m
1.76 m
1.88 m
1.86 m
1.88 m
1.83 m
1.84 m
1.75 m
1.66 m
1.9 m
1.83 m
1.76 m
1.88 m
1.83 m
1.88 m
1.8 m
1.66 m
1.84 m
1.75 m
1.88 m
1.87 m
1.83 m
1.73 m
1.71 m
1.88 m
1.86 m
1.74 m
1.9 m
1.82 m
1.83 m
1.87 m
1.95 m
1.75 m
1.86 m
1.72 m
1.81 m
1.78 m
1.88 m
1.87 m
1.81 m
1.92 m
1.87 m
1.8 m
1.89 m
1.73 m
1.82 m
1.85 m
1.78 m
1.78 m
1.93 m
1.88 m
1.78 m
1.77 m
1.77 m
1.71 m
1.77 m
1.72 m
1.88 m
1.88 m
1.66 m
1.85 m
1.75 m
1.72 m
1.83 m
1.7 m
1.9 m
1.89 m
1.83 m
1.78 m
1.92 m
1.86 m
1.86 m
1.79 m
1.73 m
1.92 m
1.93 m
1.7 m
1.87 m
1.71 m
1.8 m
1.9 m
1.85 m
1.87 m
1.8 m
1.78 m
1.8 m
1.88 m
1.7 m
1.96 m
1.79 m
1.81 m
1.86 m
1.79 m
1.82 m
1.79 m
1.78 m
1.8 m
1.7 m
1.86 m
1.94 m
1.91 m
1.76 m
1.89 m
1.73 m
1.85 m
1.74 m
1.82 m
1.9 m
1.87 m
1.85 m
1.78 m
1.89 m
1.85 m
1.83 m
1.8 m
1.84 m
1.71 m
1.87 m
1.85 m
1.83 m
1.9 m
1.88 m
1.86 m
1.82 m
1.83 m
1.97 m
1.82 m
1.75 m
1.83 m
1.81 m
1.66 m
1.75 m
1.72 m
1.73 m
1.9 m
1.83 m
1.89 m
1.85 m
1.86 m
1.82 m
1.91 m
1.76 m
1.82 m
1.72 m
1.89 m
1.81 m
1.81 m
1.87 m
1.71 m
1.81 m
1.75 m
1.86 m
1.85 m
1.84 m
1.75 m
1.75 m
1.75 m
1.87 m
1.87 m
1.91 m
1.73 m
1.87 m
1.78 m
1.71 m
1.7 m
1.68 m
1.85 m
1.88 m
1.81 m
1.75 m
1.9 m
1.73 m
1.84 m
1.91 m
1.73 m
1.86 m
1.82 m
1.67 m
1.73 m
1.84 m
1.74 m
1.73 m
1.9 m
1.83 m
1.96 m
1.74 m
1.78 m
1.9 m
1.8 m
1.89 m
1.8 m
1.87 m
1.89 m
1.78 m
1.91 m
1.74 m
1.77 m
1.78 m
1.85 m
1.85 m
1.8 m
1.88 m
1.92 m
1.75 m
1.75 m
1.87 m
1.73 m
1.84 m
1.72 m
1.78 m
1.8 m
1.8 m
1.84 m
1.71 m
1.8 m
1.9 m
1.7 m
1.78 m
1.85 m
1.73 m
1.88 m
1.87 m
1.81 m
1.98 m
1.93 m
1.78 m
1.98 m
1.78 m
1.83 m
1.78 m
1.95 m
1.79 m
1.86 m
1.82 m
1.77 m
1.84 m
1.79 m
1.9 m
1.82 m
1.74 m
1.79 m
1.73 m
1.88 m
1.83 m
1.92 m
1.85 m
1.88 m
1.7 m
1.8 m
1.91 m
1.8 m
1.8 m
1.72 m
1.85 m
1.83 m
1.87 m
1.91 m
1.9 m
1.76 m
1.82 m
1.79 m
1.78 m
1.91 m
1.69 m
1.94 m
1.74 m
1.84 m
1.75 m
1.75 m
1.69 m
1.76 m
1.79 m
1.7 m
1.74 m
1.75 m
1.82 m
1.89 m
1.71 m
1.73 m
1.85 m
1.71 m
1.94 m
1.84 m
1.78 m
1.84 m
1.84 m
1.85 m
1.88 m
1.83 m
1.78 m
1.9 m
1.73 m
1.78 m
1.72 m
1.86 m
1.81 m
1.87 m
1.87 m
1.77 m
1.88 m
1.83 m
1.93 m
1.85 m
1.83 m
1.85 m
1.78 m
1.85 m
1.81 m
1.72 m
1.86 m
1.85 m
1.9 m
1.93 m
1.9 m
1.85 m
1.92 m
1.73 m
1.92 m
1.85 m
1.76 m
1.83 m
1.71 m
1.82 m
1.81 m
1.85 m
1.84 m
1.9 m
1.82 m
1.81 m
1.73 m
1.78 m
1.91 m
1.83 m
1.77 m
1.88 m
1.91 m
1.77 m
1.82 m
1.84 m
1.92 m
1.89 m
1.75 m
1.85 m
1.82 m
1.83 m
1.85 m
1.76 m
1.76 m
1.8 m
1.75 m
1.73 m
1.89 m
1.9 m
1.78 m
1.81 m
1.84 m
1.82 m
1.75 m
1.85 m
1.83 m
1.83 m
1.91 m
1.9 m
1.93 m
1.74 m
1.91 m
1.73 m
1.82 m
1.74 m
1.85 m
1.94 m
1.74 m
1.71 m
1.77 m
1.86 m
1.85 m
1.92 m
1.83 m
1.77 m
1.75 m
1.78 m
1.75 m
1.72 m
1.8 m
1.8 m
1.77 m
1.82 m
1.85 m
1.83 m
1.86 m
1.72 m
1.85 m
1.78 m
1.87 m
1.82 m
1.83 m
1.83 m
1.75 m
1.9 m
1.77 m
1.8 m
1.86 m
1.76 m
1.79 m
1.87 m
1.9 m
1.8 m
1.7 m
1.88 m
1.8 m
1.75 m
1.88 m
1.89 m
1.9 m
1.85 m
1.93 m
1.78 m
1.75 m
1.8 m
1.83 m
1.81 m
1.71 m
1.8 m
1.78 m
1.82 m
1.89 m
1.8 m
1.75 m
1.78 m
1.88 m
1.91 m
1.9 m
1.74 m
1.7 m
1.76 m
1.68 m
1.73 m
1.78 m
1.88 m
1.86 m
1.83 m
1.86 m
1.9 m
1.73 m
1.93 m
1.77 m
1.75 m
1.78 m
1.75 m
1.77 m
1.82 m
1.83 m
1.85 m
1.82 m
1.87 m
1.69 m
1.72 m
1.75 m
1.82 m
1.87 m
1.8 m
1.82 m
1.72 m
1.7 m
1.9 m
1.9 m
1.82 m
1.88 m
1.83 m
1.82 m
1.83 m
1.87 m
1.99 m
1.76 m
1.79 m
1.78 m
1.8 m
1.86 m
1.77 m
1.75 m
1.87 m
1.82 m
1.89 m
1.8 m
1.8 m
1.92 m
1.84 m
1.89 m
1.9 m
1.82 m
1.91 m
1.83 m
1.83 m
1.93 m
1.8 m
1.72 m
1.84 m
1.82 m
1.84 m
1.85 m
1.95 m
1.79 m
1.9 m
1.84 m
1.85 m
1.83 m
1.79 m
1.8 m
1.79 m
1.76 m
2.04 m
1.7 m
1.94 m
1.93 m
1.93 m
1.92 m
1.8 m
1.82 m
1.83 m
1.78 m
1.95 m
1.73 m
1.92 m
1.74 m
1.7 m
1.87 m
1.89 m
1.78 m
1.78 m
1.86 m
1.87 m
1.84 m
1.85 m
1.77 m
2.01 m
1.8 m
1.86 m
1.83 m
1.93 m
1.76 m
1.69 m
1.75 m
1.87 m
1.82 m
1.83 m
1.79 m
1.64 m
1.88 m
1.83 m
1.87 m
1.85 m
1.82 m
1.79 m
1.75 m
1.79 m
1.85 m
1.87 m
1.87 m
1.95 m
1.85 m
1.78 m
1.84 m
1.87 m
1.87 m
1.79 m
1.69 m
1.82 m
1.82 m
1.89 m
1.72 m
1.69 m
1.88 m
1.95 m
1.84 m
1.89 m
1.84 m
1.75 m
1.8 m
1.9 m
1.82 m
1.86 m
1.9 m
1.94 m
1.81 m
1.86 m
1.8 m
1.82 m
1.73 m
1.81 m
1.96 m
1.85 m
1.81 m
1.83 m
1.78 m
1.8 m
1.68 m
1.79 m
1.89 m
1.79 m
1.8 m
1.69 m
1.83 m
1.8 m
1.87 m
1.92 m
1.86 m
1.75 m
1.78 m
1.77 m
1.92 m
1.92 m
1.84 m
1.78 m
1.88 m
1.76 m
1.8 m
1.79 m
1.96 m
1.75 m
1.92 m
1.78 m
1.85 m
1.83 m
1.8 m
1.92 m
1.81 m
1.81 m
1.87 m
1.74 m
1.76 m
1.88 m
1.7 m
1.92 m
1.85 m
1.7 m
1.83 m
1.74 m
1.86 m
1.84 m
1.75 m
1.95 m
1.8 m
1.85 m
1.77 m
1.82 m
1.76 m
1.9 m
1.87 m
1.87 m
1.88 m
1.91 m
1.7 m
1.7 m
1.79 m
1.86 m
1.84 m
1.8 m
1.89 m
1.85 m
1.74 m
1.87 m
1.91 m
1.71 m
1.9 m
1.83 m
1.84 m
1.83 m
1.78 m
1.73 m
1.9 m
1.83 m
1.91 m
1.84 m
1.73 m
1.93 m
1.75 m
1.66 m
1.84 m
1.65 m
1.8 m
1.88 m
1.74 m
1.73 m
1.66 m
1.69 m
1.59 m
1.84 m
1.78 m
1.86 m
1.78 m
1.85 m
1.82 m
1.77 m
1.88 m
1.72 m
1.77 m
1.8 m
1.78 m
1.87 m
1.78 m
1.85 m
1.74 m
1.79 m
1.91 m
1.93 m
1.82 m
1.97 m
1.84 m
1.8 m
2.03 m
1.79 m
1.85 m
1.88 m
1.82 m
1.81 m
1.77 m
1.77 m
1.91 m
1.91 m
1.93 m
1.88 m
1.77 m
1.89 m
1.71 m
1.74 m
1.84 m
1.93 m
1.86 m
1.89 m
1.75 m
1.81 m
1.88 m
1.82 m
1.83 m
1.74 m
1.84 m
1.85 m
1.82 m
1.68 m
1.81 m
1.7 m
1.86 m
1.74 m
1.76 m
1.84 m
1.94 m
1.9 m
1.9 m
1.87 m
1.91 m
1.79 m
1.88 m
1.8 m
1.86 m
1.8 m
1.81 m
1.68 m
1.9 m
1.9 m
1.81 m
1.84 m
1.88 m
1.9 m
1.9 m
1.83 m
1.85 m
1.87 m
1.78 m
1.78 m
1.79 m
1.95 m
1.76 m
1.88 m
1.8 m
1.75 m
1.7 m
1.85 m
1.72 m
1.84 m
1.73 m
1.72 m
1.89 m
1.77 m
1.84 m
1.8 m
1.87 m
1.83 m
1.75 m
1.77 m
1.9 m
1.86 m
1.87 m
1.85 m
1.7 m
1.86 m
1.76 m
1.69 m
1.69 m
1.8 m
1.79 m
1.75 m
1.89 m
1.73 m
1.88 m
1.78 m
1.9 m
1.93 m
1.71 m
1.8 m
1.95 m
1.85 m
1.88 m
1.69 m
1.91 m
1.86 m
1.88 m
1.81 m
1.71 m
1.87 m
1.81 m
1.83 m
1.92 m
1.8 m
1.85 m
1.89 m
1.73 m
1.84 m
1.82 m
1.74 m
1.8 m
1.87 m
1.91 m
1.85 m
1.8 m
1.78 m
1.84 m
1.84 m
1.7 m
1.94 m
1.81 m
1.9 m
1.77 m
1.86 m
1.86 m
1.74 m
2.0 m
1.75 m
1.89 m
1.98 m
1.8 m
1.82 m
1.92 m
1.87 m
1.83 m
1.91 m
1.82 m
1.85 m
1.84 m
1.77 m
1.93 m
1.82 m
1.78 m
1.91 m
1.88 m
1.73 m
1.89 m
1.85 m
1.84 m
1.85 m
1.9 m
1.68 m
1.79 m
1.88 m
1.72 m
1.74 m
1.79 m
1.86 m
1.79 m
1.78 m
1.84 m
1.86 m
1.8 m
1.91 m
1.82 m
1.92 m
1.8 m
1.79 m
1.88 m
1.76 m
1.73 m
1.93 m
1.91 m
1.92 m
1.75 m
1.78 m
1.85 m
1.73 m
1.78 m
1.7 m
1.73 m
1.9 m
1.87 m
1.88 m
1.9 m
1.85 m
1.78 m
1.78 m
1.88 m
1.81 m
1.84 m
1.72 m
1.69 m
1.8 m
1.88 m
1.8 m
1.86 m
1.8 m
1.79 m
1.73 m
1.78 m
1.81 m
1.7 m
1.87 m
1.82 m
1.85 m
1.86 m
1.8 m
1.85 m
1.8 m
1.7 m
1.8 m
1.83 m
1.75 m
1.79 m
1.74 m
1.75 m
1.97 m
1.75 m
1.8 m
1.88 m
1.86 m
1.76 m
1.85 m
1.89 m
1.85 m
1.62 m
1.69 m
1.76 m
1.85 m
1.74 m
1.87 m
1.86 m
1.94 m
1.89 m
1.96 m
1.9 m
1.86 m
1.86 m
1.77 m
1.95 m
1.92 m
1.84 m
1.86 m
1.85 m
1.91 m
1.86 m
1.88 m
1.82 m
1.93 m
1.81 m
1.69 m
1.79 m
1.85 m
1.85 m
1.92 m
1.82 m
1.7 m
1.84 m
1.78 m
1.81 m
1.74 m
1.78 m
1.88 m
1.94 m
1.83 m
1.93 m
1.74 m
1.88 m
1.71 m
1.74 m
1.96 m
1.78 m
1.79 m
1.75 m
1.8 m
1.8 m
1.7 m
1.94 m
1.87 m
1.79 m
1.82 m
1.83 m
1.64 m
1.84 m
1.68 m
1.82 m
1.8 m
1.85 m
1.8 m
1.7 m
1.85 m
1.73 m
1.87 m
1.93 m
1.86 m
1.83 m
1.78 m
1.71 m
1.82 m
1.86 m
1.82 m
1.85 m
1.88 m
1.78 m
1.8 m
1.75 m
1.87 m
1.85 m
1.93 m
1.85 m
1.88 m
1.78 m
1.75 m
1.93 m
1.86 m
1.85 m
1.88 m
1.92 m
1.78 m
1.79 m
1.81 m
1.91 m
1.66 m
1.82 m
1.79 m
1.87 m
1.73 m
1.84 m
1.87 m
1.84 m
1.74 m
1.89 m
1.9 m
1.75 m
1.77 m
1.81 m
1.86 m
1.75 m
1.88 m
1.65 m
1.91 m
1.8 m
1.83 m
1.78 m
1.81 m
1.75 m
1.83 m
1.71 m
1.86 m
1.82 m
1.8 m
1.95 m
1.78 m
1.82 m
1.83 m
1.89 m
1.85 m
1.7 m
1.78 m
1.8 m
1.87 m
1.83 m
1.75 m
1.88 m
1.78 m
1.88 m
1.88 m
1.98 m
1.67 m
1.85 m
1.78 m
1.92 m
1.85 m
1.83 m
1.81 m
1.78 m
1.93 m
1.96 m
1.87 m
1.74 m
1.8 m
1.72 m
1.72 m
1.86 m
1.75 m
1.86 m
1.82 m
1.85 m
1.73 m
1.7 m
1.81 m
1.94 m
1.84 m
1.81 m
1.85 m
1.63 m
1.91 m
1.86 m
1.91 m
1.87 m
1.83 m
1.88 m
1.76 m
1.82 m
1.82 m
1.72 m
1.93 m
1.74 m
1.82 m
1.81 m
1.85 m
1.75 m
1.9 m
1.85 m
1.88 m
1.88 m
1.75 m
1.75 m
1.71 m
1.81 m
1.75 m
1.83 m
1.84 m
1.7 m
1.86 m

## Generación de Inserts

### Nations

```sql
CREATE TABLE nations (
  id	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  name	VARCHAR(40)
);

-- migrate:up

INSERT INTO nations (id, name) VALUES (1, 'Albania');
INSERT INTO nations (id, name) VALUES (2, 'Argelia');
...

-- migrate:down

DELETE FROM nations;

```

In [3]:
tmp = ds_players['Nation']
nations = sorted(list(tmp.unique()))

text = '-- migrate:up \n\n'
id = 1
nations_dicc = {}

for n in nations:
  name = n.replace("'", "''")
  text = text + f"INSERT INTO nations (id, name) VALUES ({id}, '{name}');\n"
  nations_dicc[name] = id
  id = id + 1
text = text + '\n-- migrate:down \n\nDELETE FROM nations;'
with open('inserts_nations.sql', 'w') as archivo:
  archivo.write(text)

### Positions

```sql
CREATE TABLE positions (
  id	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  name	VARCHAR(10)
);
```

In [4]:
tmp = ds_players['Position']
positions = sorted(list(tmp.unique()))

text = '-- migrate:up \n\n'
id = 1

positions_dicc = {}

for name in positions:
  text = text + f"INSERT INTO positions (id, name) VALUES ({id}, '{name}');\n"
  positions_dicc[name] = id
  id = id + 1
text = text + '\n-- migrate:down \n\nDELETE FROM positions;'
with open('inserts_positions.sql', 'w') as archivo:
  archivo.write(text)

### Foots

```sql
CREATE TABLE foots (
  id	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  name	VARCHAR(6)
);
```

In [5]:
tmp = ds_players['Preferred foot']
foots = list(tmp.unique())

text = '-- migrate:up \n\n'
id = 1
for name in foots:
  text = text + f"INSERT INTO foots (id, name) VALUES ({id}, '{name}');\n"
  id = id + 1
text = text + '\n-- migrate:down \n\nDELETE FROM foots;'
with open('inserts_foots.sql', 'w') as archivo:
  archivo.write(text)

### Sexs

```sql
CREATE TABLE sexs (
  id	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  name	VARCHAR(7)
);
```

In [6]:
sexs = ['Male', 'Female']

text = '-- migrate:up \n\n'
id = 1
for name in sexs:
  text = text + f"INSERT INTO sexs (id, name) VALUES ({id}, '{name}');\n"
  id = id + 1
text = text + '\n-- migrate:down \n\nDELETE FROM sexs;'
with open('inserts_sexs.sql', 'w') as archivo:
  archivo.write(text)

### Play Styles

```sql
CREATE TABLE play_styles (
  id	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  name	VARCHAR(30)
);
```

In [33]:
tmp = ds_players['play style']
play_styles_mam = list(tmp)

play_styles = []
for t in play_styles_mam:
    if isinstance(t, str):
        tmp2 = t.split(', ')
        for style in tmp2:
            if style not in play_styles:
                play_styles.append(style)

play_styles = sorted(play_styles)

play_styles_dicc = {}

text = '-- migrate:up \n\n'
id = 1
for name in play_styles:
  text = text + f"INSERT INTO play_styles (id, name) VALUES ({id}, '{name}');\n"
  play_styles_dicc[name] = id
  id = id + 1
text = text + '\n-- migrate:down \n\nDELETE FROM play_styles;'
with open('inserts_play_styles.sql', 'w') as archivo:
  archivo.write(text)

print(play_styles_dicc)

{'1v1 Close Down': 1, '1v1 Close Down+': 2, 'Acrobatic': 3, 'Acrobatic+': 4, 'Aerial': 5, 'Aerial+': 6, 'Anticipate': 7, 'Anticipate+': 8, 'Block': 9, 'Block+': 10, 'Bruiser': 11, 'Bruiser+': 12, 'Chip Shot': 13, 'Chip Shot+': 14, 'Cross Claimer': 15, 'Cross Claimer+': 16, 'Dead Ball': 17, 'Dead Ball+': 18, 'Deflector': 19, 'Deflector+': 20, 'Far Reach': 21, 'Far Reach+': 22, 'Far Throw': 23, 'Far Throw+': 24, 'Finesse Shot': 25, 'Finesse Shot+': 26, 'First Touch': 27, 'First Touch+': 28, 'Flair': 29, 'Flair+': 30, 'Footwork': 31, 'Footwork+': 32, 'Incisive Pass': 33, 'Incisive Pass+': 34, 'Intercept': 35, 'Intercept+': 36, 'Jockey': 37, 'Jockey+': 38, 'Long Ball Pass': 39, 'Long Ball Pass+': 40, 'Long Throw': 41, 'Long Throw+': 42, 'Pinged Pass': 43, 'Pinged Pass+': 44, 'Power Header': 45, 'Power Header+': 46, 'Power Shot': 47, 'Power Shot+': 48, 'Press Proven': 49, 'Press Proven+': 50, 'Quick Step': 51, 'Quick Step+': 52, 'Rapid': 53, 'Rapid+': 54, 'Relentless': 55, 'Relentless+': 56, 'Slide Tackle': 57, 'Slide Tackle+': 58, 'Technical': 59, 'Technical+': 60, 'Tiki Taka': 61, 'Tiki Taka+': 62, 'Trickster': 63, 'Trickster+': 64, 'Trivela': 65, 'Trivela+': 66, 'Whipped Pass': 67, 'Whipped Pass+': 68}

### Leagues

```sql
CREATE TABLE leagues (
  id	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  name	VARCHAR(30),
  nation_id	INTEGER,
  FOREIGN KEY (nation_id) REFERENCES nations (id)
);
```

In [8]:
tmp = ds_players['League']
leagues = list(tmp.unique())
leagues = sorted(leagues)
leagues_dicc = {}

text = '-- migrate:up \n\n'
id = 1
for name in leagues:
  name = name.replace("'", "''")
  text = text + f"INSERT INTO leagues (id, name, nation_id) VALUES ({id}, '{name}', 1);\n"
  leagues_dicc[name] = id
  id = id + 1
text = text + '\n-- migrate:down \n\nDELETE FROM leagues;'
with open('inserts_leagues.sql', 'w', encoding='utf-8') as archivo:
  archivo.write(text)

leagues_dicc

{'1A Pro League': 1,
 '3. Liga': 2,
 '3F Superliga': 3,
 'A-League': 4,
 'Allsvenskan': 5,
 'Arkema PL': 6,
 'Barclays WSL': 7,
 'Bundesliga': 8,
 'Bundesliga 2': 9,
 'CSL': 10,
 'CSSL': 11,
 'Calcio A Femminile': 12,
 'Ceska Liga Žen': 13,
 'EFL Championship': 14,
 'EFL League One': 15,
 'EFL League Two': 16,
 'Eliteserien': 17,
 'Eredivisie': 18,
 'Finnliiga': 19,
 'GPFBL': 20,
 'Hellas Liga': 21,
 'ISL': 22,
 'K League 1': 23,
 'LALIGA EA SPORTS': 24,
 'LALIGA HYPERMOTION': 25,
 'Libertadores': 26,
 'Liga Azerbaijan': 27,
 'Liga Colombia': 28,
 'Liga Cyprus': 29,
 'Liga F': 30,
 'Liga Hrvatska': 31,
 'Liga Portugal': 32,
 'Liga Portugal Feminino': 33,
 "Ligue 1 McDonald''s": 34,
 'Ligue 2 BKT': 35,
 'MLS': 36,
 'Magyar Liga': 37,
 'NWSL': 38,
 'Nederland Vrouwen Liga': 39,
 'PKO BP Ekstraklasa': 40,
 'Premier League': 41,
 'Primera División': 42,
 'ROSHN Saudi League': 43,
 'SSE Airtricity PD': 44,
 'SUPERLIGA': 45,
 'Schweizer Damen Liga': 46,
 'Scottish Prem': 47,
 "Scottish Women''s League": 48,
 'Serie A Enilive': 49,
 'Serie BKT': 50,
 'Sudamericana': 51,
 'Sverige Liga': 52,
 'Trendyol Süper Lig': 53,
 'Ukrayina Liha': 54,
 'United Emirates League': 55,
 'Ö. Bundesliga': 56,
 'Česká Liga': 57}

### Teams

```sql
CREATE TABLE teams (
  id	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  name	VARCHAR(40),
  league_id	INTEGER NOT NULL,
  FOREIGN KEY (league_id) REFERENCES leagues (id)
);
```

In [9]:
tmp = ds_players[['League', 'Team']]

text = '-- migrate:up \n\n'
id = 1

tmp_lista = []
teams_dicc = {}

for _, row in tmp.iterrows():

  league = row['League'].replace("'", "''")
  team = row['Team'].replace("'", "''")

  if league + team not in tmp_lista:
    tmp_lista.append(league + team)
    league_id = leagues_dicc[league]
    teams_dicc[team] = id
    text = text + f"INSERT INTO teams (id, name, league_id) VALUES ({id}, '{team}', {league_id});\n"
    id = id + 1

text = text + '\n-- migrate:down \n\nDELETE FROM teams;'
with open('inserts_teams.sql', 'w', encoding='utf-8') as archivo:
  archivo.write(text)

## Llenar Jugadores

```sql
CREATE TABLE players (
  id	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  name	VARCHAR(60),
  rank INTEGER,
  weak_foot INTEGER,
  skill_moves INTEGER,
  heigth INTEGER,
  weight INTEGER,
  age INTEGER,
  url VARCHAR(120),
  foot_id INTEGER NOT NULL,
  sex_id INTEGER NOT NULL,
  position_id INTEGER NOT NULL,
  nation_id	INTEGER NOT NULL,
  team_id	INTEGER NOT NULL,
  FOREIGN KEY (foot_id) REFERENCES foots (id),
  FOREIGN KEY (sex_id) REFERENCES sexs (id),
  FOREIGN KEY (position_id) REFERENCES positions (id),
  FOREIGN KEY (nation_id) REFERENCES nations (id)
  FOREIGN KEY (team_id) REFERENCES teams (id)
);

CREATE TABLE common_details (
  id	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  overall INTEGER, -- OVR
  velocity INTEGER, -- PAC
  shooting INTEGER, -- SHO
  passing INTEGER,  -- PAS
  dribbling INTEGER, -- DRI
  defending INTEGER, -- DEF
  physicality INTEGER, -- PHY
  player_id	INTEGER NOT NULL,
  FOREIGN KEY (player_id) REFERENCES players (id)
);

CREATE TABLE goalkeeper_details (
  id	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  diving INTEGER,
  handling INTEGER,
  kicking INTEGER,
  positioning INTEGER,
  reflexes INTEGER,
  player_id	INTEGER NOT NULL,
  FOREIGN KEY (player_id) REFERENCES players (id)
);
```

In [36]:
# =====================================
# GENERAR INSERTS:
# - players
# - common_details
# - goalkeeper_details
# =====================================

players_text = '-- migrate:up\n\n'
common_text = '-- migrate:up\n\n'
goalkeeper_text = '-- migrate:up\n\n'

id = 1

foot_dicc = {
    'Right': 1,
    'Left': 2
}

# =====================================
# MALE PLAYERS
# =====================================

tmp = ds_males[
    [
        'Name', 'Rank', 'Weak foot', 'Height', 'Weight', 'Age',
        'Preferred foot', 'Position', 'Nation', 'Team', 'url',
        'OVR', 'PAC', 'SHO', 'PAS', 'DRI', 'DEF', 'PHY',
        'GK Diving', 'GK Handling', 'GK Kicking',
        'GK Positioning', 'GK Reflexes'
    ]
]

for _, row in tmp.iterrows():

    name = row['Name'].replace("'", "''")
    rank = row['Rank']
    weak_foot = row['Weak foot']
    height = int(str(row['Height'])[:3])
    weight = int(str(row['Weight']).split('kg')[0])
    age = row['Age']
    url = row['url']

    foot_id = foot_dicc[row['Preferred foot']]
    sex_id = 1

    position = row['Position']
    position_id = positions_dicc[position]

    nation_id = nations_dicc[row['Nation'].replace("'", "''")]
    team_id = teams_dicc[row['Team'].replace("'", "''")]

    # ==========================
    # PLAYERS
    # ==========================

    players_text += (
        f"INSERT INTO players "
        f"(id, name, rank, weak_foot, heigth, weight, age, foot_id, url, "
        f"sex_id, position_id, nation_id, team_id) "
        f"VALUES ("
        f"{id}, "
        f"'{name}', "
        f"{rank}, "
        f"{weak_foot}, "
        f"{height}, "
        f"{weight}, "
        f"{age}, "
        f"{foot_id}, "
        f"'{url}', "
        f"{sex_id}, "
        f"{position_id}, "
        f"{nation_id}, "
        f"{team_id}"
        f");\n"
    )

    # ==========================
    # COMMON DETAILS
    # ==========================

    common_text += (
        f"INSERT INTO common_details "
        f"(overall, velocity, shooting, passing, dribbling, defending, physicality, player_id) "
        f"VALUES ("
        f"{row['OVR']}, "
        f"{row['PAC']}, "
        f"{row['SHO']}, "
        f"{row['PAS']}, "
        f"{row['DRI']}, "
        f"{row['DEF']}, "
        f"{row['PHY']}, "
        f"{id}"
        f");\n"
    )

    # ==========================
    # GOALKEEPER DETAILS
    # ==========================

    if position == 'GK':

        goalkeeper_text += (
            f"INSERT INTO goalkeeper_details "
            f"(diving, handling, kicking, positioning, reflexes, player_id) "
            f"VALUES ("
            f"{row['GK Diving']}, "
            f"{row['GK Handling']}, "
            f"{row['GK Kicking']}, "
            f"{row['GK Positioning']}, "
            f"{row['GK Reflexes']}, "
            f"{id}"
            f");\n"
        )

    id += 1

# =====================================
# FEMALE PLAYERS
# =====================================

tmp = ds_females[
    [
        'Name', 'Rank', 'Weak foot', 'Height', 'Weight', 'Age',
        'Preferred foot', 'Position', 'Nation', 'Team', 'url',
        'OVR', 'PAC', 'SHO', 'PAS', 'DRI', 'DEF', 'PHY',
        'GK Diving', 'GK Handling', 'GK Kicking',
        'GK Positioning', 'GK Reflexes'
    ]
]

for _, row in tmp.iterrows():

    name = row['Name'].replace("'", "''")
    rank = row['Rank']
    weak_foot = row['Weak foot']
    height = int(str(row['Height'])[:3])
    weight = int(str(row['Weight']).split('kg')[0])
    age = row['Age']
    url = row['url']

    foot_id = foot_dicc[row['Preferred foot']]
    sex_id = 2

    position = row['Position']
    position_id = positions_dicc[position]

    nation_id = nations_dicc[row['Nation'].replace("'", "''")]
    team_id = teams_dicc[row['Team'].replace("'", "''")]

    # ==========================
    # PLAYERS
    # ==========================

    players_text += (
        f"INSERT INTO players "
        f"(id, name, rank, weak_foot, heigth, weight, age, foot_id, url, "
        f"sex_id, position_id, nation_id, team_id) "
        f"VALUES ("
        f"{id}, "
        f"'{name}', "
        f"{rank}, "
        f"{weak_foot}, "
        f"{height}, "
        f"{weight}, "
        f"{age}, "
        f"{foot_id}, "
        f"'{url}', "
        f"{sex_id}, "
        f"{position_id}, "
        f"{nation_id}, "
        f"{team_id}"
        f");\n"
    )

    # ==========================
    # COMMON DETAILS
    # ==========================

    common_text += (
        f"INSERT INTO common_details "
        f"(overall, velocity, shooting, passing, dribbling, defending, physicality, player_id) "
        f"VALUES ("
        f"{row['OVR']}, "
        f"{row['PAC']}, "
        f"{row['SHO']}, "
        f"{row['PAS']}, "
        f"{row['DRI']}, "
        f"{row['DEF']}, "
        f"{row['PHY']}, "
        f"{id}"
        f");\n"
    )

    # ==========================
    # GOALKEEPER DETAILS
    # ==========================

    if position == 'GK':

        goalkeeper_text += (
            f"INSERT INTO goalkeeper_details "
            f"(diving, handling, kicking, positioning, reflexes, player_id) "
            f"VALUES ("
            f"{row['GK Diving']}, "
            f"{row['GK Handling']}, "
            f"{row['GK Kicking']}, "
            f"{row['GK Positioning']}, "
            f"{row['GK Reflexes']}, "
            f"{id}"
            f");\n"
        )

    id += 1

# =====================================
# MIGRATE DOWN
# =====================================

players_text += '\n-- migrate:down\n\nDELETE FROM players;'
common_text += '\n-- migrate:down\n\nDELETE FROM common_details;'
goalkeeper_text += '\n-- migrate:down\n\nDELETE FROM goalkeeper_details;'

# =====================================
# GENERAR ARCHIVOS
# =====================================

with open('inserts_players.sql', 'w', encoding='utf-8') as archivo:
    archivo.write(players_text)

with open('inserts_common_details.sql', 'w', encoding='utf-8') as archivo:
    archivo.write(common_text)

with open('inserts_goalkeeper_details.sql', 'w', encoding='utf-8') as archivo:
    archivo.write(goalkeeper_text)

print('Archivos generados correctamente.')

Archivos generados correctamente.

## Players Play Styles

```sql
CREATE TABLE players_play_styles (
  id	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  play_style_id	INTEGER NOT NULL,
  player_id	INTEGER NOT NULL,
  FOREIGN KEY (play_style_id) REFERENCES play_styles (id),
  FOREIGN KEY (player_id) REFERENCES players (id)
);
```

In [34]:
text = '-- migrate:up \n\n'
id = 1
player_id = 1

# males players
tmp = ds_males[['play style']]

for _, row in tmp.iterrows():
  if isinstance (row['play style'], str):
    # si jugador tiene estilos de juego, crear 
    for play_style in row['play style'].split(', '):
      play_style_id = play_styles_dicc[play_style]

      text = text + f"INSERT INTO players_play_styles (id, play_style_id, player_id) VALUES ({id}, {play_style_id}, {player_id});\n"

      id = id + 1
    # siguiente jugador
    player_id = player_id + 1

# females players
tmp = ds_females[['play style']]

for _, row in tmp.iterrows():
  if isinstance (row['play style'], str):
    # si jugador tiene estilos de juego, crear 
    for play_style in row['play style'].split(', '):
      play_style_id = play_styles_dicc[play_style]

      text = text + f"INSERT INTO players_play_styles (id, play_style_id, player_id) VALUES ({id}, {play_style_id}, {player_id});\n"

      id = id + 1
    # siguiente jugador
    player_id = player_id + 1

text = text + '\n-- migrate:down \n\nDELETE FROM players_play_styles;'
with open('inserts_players_play_styles.sql', 'w', encoding='utf-8') as archivo:
  archivo.write(text)

## Players Positions

```sql
CREATE TABLE players_positions (
  id	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  position_id	INTEGER NOT NULL,
  player_id	INTEGER NOT NULL,
  FOREIGN KEY (position_id) REFERENCES positions (id),
  FOREIGN KEY (player_id) REFERENCES players (id)
);
```

In [ ]:
text = '-- migrate:up \n\n'
id = 1
player_id = 1

# males players
tmp = ds_males[['Alternative positions']]

for _, row in tmp.iterrows():
  if isinstance (row['Alternative positions'], str):
    # si jugador tiene estilos de juego, crear 
    for position in row['Alternative positions'].split(', '):
      position_id = positions_dicc[position]

      text = text + f"INSERT INTO players_positions (id, position_id, player_id) VALUES ({id}, {position_id}, {player_id});\n"

      id = id + 1
    # siguiente jugador
    player_id = player_id + 1

# females players
tmp = ds_females[['Alternative positions']]

for _, row in tmp.iterrows():
  if isinstance (row['Alternative positions'], str):
    # si jugador tiene estilos de juego, crear 
    for position in row['Alternative positions'].split(', '):
      position_id = positions_dicc[position]

      text = text + f"INSERT INTO players_positions (id, position_id, player_id) VALUES ({id}, {position_id}, {player_id});\n"

      id = id + 1
    # siguiente jugador
    player_id = player_id + 1

text = text + '\n-- migrate:down \n\nDELETE FROM players_positions;'
with open('inserts_players_positions.sql', 'w', encoding='utf-8') as archivo:
  archivo.write(text)

# Generar Datos

In [81]:
from faker import Faker
import random

fake = Faker()

Prueba

In [79]:
fake.address()
fake.name_male()

'Gary Murray'

In [86]:
players_text = '-- migrate:up\n\n'

id = 17738

for i in range(100):

    name = fake.name_male()
    rank = 17717 + (i+1)
    weak_foot = random.randint(1,5)
    height = random.randint(150,201)
    weight = random.randint(40,100)
    age = random.randint(15,41)
    url = fake.image_url()

    foot_id = random.randint(1,2)
    sex_id = random.randint(1,2)

    if sex_id == 2:
        name = fake.name_female()

    position_id = random.randint(1,12)

    nation_id = random.randint(1,154)
    team_id = random.randint(1,735)

    # ==========================
    # PLAYERS
    # ==========================

    players_text += (
        f"INSERT INTO players "
        f"(id, name, rank, weak_foot, heigth, weight, age, foot_id, url, "
        f"sex_id, position_id, nation_id, team_id) "
        f"VALUES ("
        f"{id}, "
        f"'{name}', "
        f"{rank}, "
        f"{weak_foot}, "
        f"{height}, "
        f"{weight}, "
        f"{age}, "
        f"{foot_id}, "
        f"'{url}', "
        f"{sex_id}, "
        f"{position_id}, "
        f"{nation_id}, "
        f"{team_id}"
        f");\n"
    )

    id = id + 1

players_text = players_text + '\n-- migrate:down \n\nDELETE FROM players WHERE id >= 17738;'
with open('inserts_extra_players.sql', 'w', encoding='utf-8') as archivo:
  archivo.write(players_text)